### ISSUE TITLE
DNN File Upload - specifying folderName breaks upload

### ISSUE THREAD

**Issue by itsMigo** [dnnsoftware/Dnn.React.Common#137]
When passing a folderName to the dnn-file-upload component, the upload fails. 
![dnnfileuploadbad](https://user-images.githubusercontent.com/8866084/36365902-6cc0ec32-1500-11e8-8dfc-1ee7cdb86589.PNG)

Expected: Specifying a folderName uploads folders into this folder.

**Comment by valadas** [comment]
@itsMigo 
It will not work with only a folder name. Folder names are not garanteed to be unique.
There is a FileDTO you need to use that has fileId, fileName, folderId and folderPath, you need to pass that object to the selectedFile property of the component.

Look at this pull request I submitted for bringing back page icons and you should have a good working example: https://github.com/dnnsoftware/Dnn.AdminExperience/commit/192719fff884395850bc625f95ade6633f7b2f5f

**Comment by valadas** [comment]
I am closing this issue to cleanup @itsMigo feel free to open another issue if my answer did not cover your use case
