### ISSUE TITLE
dnn-webpack-externals peer dependecies for eslint and web pack are extremely old

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.React.Common#148]
The versions of the peer dependencies for dnn-webpack-externals needs to be updated.

eslint-import-resolver-webpack@^0.3.2 but is currently on version 0.10.1
eslint-plugin-import@^1.10.1 but is currently on version 2.13.0
eslint-plugin-react@^5.1.1 but is currently on version 7.10.0
eslint-plugin-spellcheck@^0.0.7 but is currently on version 0.0.10

eslint-plugin-spellcheck dependecy should probably be `~` and not `^`

Some of those depnded on webpack v1, but webpack v2 has been out for a while.

**Comment by mtrutledge** [comment]
I am currently working on updating all components and dependencies. I will submit another issue that this should really be a single library with components inside of it instead of having a ton of separate components.

**Comment by valadas** [comment]
@mtrutledge can we close this?

**Comment by mtrutledge** [comment]
Closing this as it was resolved with another issue
