### ISSUE TITLE
Pager component is having warnings in console that "Can't call setState on a component that is not yet mounted" and "a unique 'key' prop."

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.React.Common#195]
## Describe the bug
When going on any admin page in PB (Persona Bar) using pager component. In browser seeing warning 
"
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Pager component."

Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `Pager`.

## To Reproduce
Go to any page in PB containing pager component i.e. 
- PB > Manage > Users
- PB > Manage > Roles

## Expected behavior
Should not have these warning possible leading towards memory leak issue in react application

## Error log
Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the Pager component."

Warning: Each child in an array or iterator should have a unique "key" prop.
Check the render method of `Pager`.

**Comment by valadas** [comment]
#202 should have closed this issue
