### ISSUE TITLE
getBoundingClientRect issue when using TextOverflowWrapper

### ISSUE THREAD

**Issue by Mhtshum** [dnnsoftware/Dnn.React.Common#208]
## Describe the bug
getBoundingClientRect of null issue when using TextOverflowWrapper
PB > Settings > Servers > System Info > Database displays console errors

## To Reproduce
1.  Login as host
2. Go to PB > Settings > Servers > System Info 
3. Open browser debugger 
4. Click on Database tab and then on Web and then again on Database tab
5. See error in debugger

## Expected behavior
This getBoundingClientRect  should not appear

## Screenshots
![image](https://user-images.githubusercontent.com/43787378/51493808-b058cc00-1de0-11e9-83c1-3473fcf30960.png)

## Error log
ncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at export-bundle.js?cdv=52:1

**Comment by nvisionative** [comment]
Merged to release/9.3.0 - manually closing issue
