### ISSUE TITLE
Collapsible Content in PagePicker is hiding borders when used

### ISSUE THREAD

**Issue by mtrutledge** [dnnsoftware/Dnn.React.Common#217]
## Describe the bug
Missing border-bottom style on all dropdown fields in Site Settings > Site Behavior > DEFAULT PAGES

This issue relates to
https://github.com/dnnsoftware/Dnn.AdminExperience/issues/368

## To Reproduce
List the steps to reproduce the behavior:

Login as host
Go to Site Settings in PersonaBar
Select Site Behavior tab
View DEFAULT PAGES tab
View all dropdown fields

## Expected behavior
The borders on the dropdowns should be shown

**Comment by valadas** [comment]
Manually closing since PR got merged
