### ISSUE TITLE
Page picker not showing

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.React.Common#220]
## Describe the bug
https://github.com/dnnsoftware/Dnn.React.Common/pull/218/files appears to have been done only for the dropdowns in the permission grid. The page pickers elsewhere no longer show after that PR.

## To Reproduce
1. Get this RC build https://dev.azure.com/dotnet/DNN/_build/results?buildId=9554
2. Try to use page pickers in the pages module (parent page) or in Security, redirect after login
3. Notice the page picker does not show.

## Expected behavior
Page picker should show

## Additional context
It is just a Css issue, the other pull request is ok but did not fix all the page pickers.
I am submitting another PR in a few minutes...

**Comment by daguiler** [comment]
Closing as PR was approved and merged.
